# Generated by Django 3.1.1 on 2020-10-05 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_auto_20180423_0727'),
        ('profiles', '0011_accountstatus_user_name'),
    ]

    operations = [
    ]
